---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-docs-mdstorage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/minikube/docs"