kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "maDocK8s-controller.name" . }}
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps", ""]
    resources:
      - services
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["create", "update", "delete"]