kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "env-exporter.name" . }}
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["get"]
