# Default values for swagger-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maibornwolff/madock8s_swagger_exporter
  tag: latest
  pullPolicy: Never

arguments: ['--storage-address', 'mdstorage:80']

env:
  swaggerJsonURL: #https://petstore.swagger.io/v2/swagger.json
  swaggerPort: 81
  baseURL: /docs
  swaggerJSON: /swagger.json
  deletionStrategy: UPDATE # UPDATE | IGNORE | DELETE

madock8sID: "swaggerExporter"

annotations:
  githubExporter:
    githuburl: https://api.github.com/repos/MaibornWolff/madock8s/contents/exporter/swagger
  gitlabExporter:
    baseurl: "https://git.maibornwolff.de/api/v4/projects/3206/repository/"
    path: "exporter/swagger"
    recursive: "false"
    ref: "master"
    pattern: ".\\.md"
  envExporter:
    deployment: swagger-exporter

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
