// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: services/mdstorage.proto

package mdstorage

import (
	context "context"
	protocol "github.com/MaibornWolff/maDocK8s/core/types/protocol"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StoreResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size     int32  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *StoreResult) Reset() {
	*x = StoreResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_mdstorage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResult) ProtoMessage() {}

func (x *StoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_services_mdstorage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResult.ProtoReflect.Descriptor instead.
func (*StoreResult) Descriptor() ([]byte, []int) {
	return file_services_mdstorage_proto_rawDescGZIP(), []int{0}
}

func (x *StoreResult) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoreResult) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type RemoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveResult) Reset() {
	*x = RemoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_mdstorage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResult) ProtoMessage() {}

func (x *RemoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_services_mdstorage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResult.ProtoReflect.Descriptor instead.
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return file_services_mdstorage_proto_rawDescGZIP(), []int{1}
}

var File_services_mdstorage_proto protoreflect.FileDescriptor

var file_services_mdstorage_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x64, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x64, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d,
	0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xc5, 0x01,
	0x0a, 0x09, 0x6d, 0x64, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e,
	0x1a, 0x16, 0x2e, 0x6d, 0x64, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x1a, 0x16,
	0x2e, 0x6d, 0x64, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x1a, 0x17, 0x2e, 0x6d,
	0x64, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x69, 0x62, 0x6f, 0x72, 0x6e, 0x57, 0x6f, 0x6c, 0x66, 0x66,
	0x2f, 0x6d, 0x61, 0x44, 0x6f, 0x63, 0x4b, 0x38, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x64,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_mdstorage_proto_rawDescOnce sync.Once
	file_services_mdstorage_proto_rawDescData = file_services_mdstorage_proto_rawDesc
)

func file_services_mdstorage_proto_rawDescGZIP() []byte {
	file_services_mdstorage_proto_rawDescOnce.Do(func() {
		file_services_mdstorage_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_mdstorage_proto_rawDescData)
	})
	return file_services_mdstorage_proto_rawDescData
}

var file_services_mdstorage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_mdstorage_proto_goTypes = []interface{}{
	(*StoreResult)(nil),       // 0: mdstorage.StoreResult
	(*RemoveResult)(nil),      // 1: mdstorage.RemoveResult
	(*protocol.Markdown)(nil), // 2: protocol.Markdown
}
var file_services_mdstorage_proto_depIdxs = []int32{
	2, // 0: mdstorage.mdstorage.StoreMarkdown:input_type -> protocol.Markdown
	2, // 1: mdstorage.mdstorage.UpdateMarkdown:input_type -> protocol.Markdown
	2, // 2: mdstorage.mdstorage.DeleteMarkdown:input_type -> protocol.Markdown
	0, // 3: mdstorage.mdstorage.StoreMarkdown:output_type -> mdstorage.StoreResult
	0, // 4: mdstorage.mdstorage.UpdateMarkdown:output_type -> mdstorage.StoreResult
	1, // 5: mdstorage.mdstorage.DeleteMarkdown:output_type -> mdstorage.RemoveResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_mdstorage_proto_init() }
func file_services_mdstorage_proto_init() {
	if File_services_mdstorage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_mdstorage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_mdstorage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_mdstorage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_mdstorage_proto_goTypes,
		DependencyIndexes: file_services_mdstorage_proto_depIdxs,
		MessageInfos:      file_services_mdstorage_proto_msgTypes,
	}.Build()
	File_services_mdstorage_proto = out.File
	file_services_mdstorage_proto_rawDesc = nil
	file_services_mdstorage_proto_goTypes = nil
	file_services_mdstorage_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MdstorageClient is the client API for Mdstorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MdstorageClient interface {
	StoreMarkdown(ctx context.Context, in *protocol.Markdown, opts ...grpc.CallOption) (*StoreResult, error)
	UpdateMarkdown(ctx context.Context, in *protocol.Markdown, opts ...grpc.CallOption) (*StoreResult, error)
	DeleteMarkdown(ctx context.Context, in *protocol.Markdown, opts ...grpc.CallOption) (*RemoveResult, error)
}

type mdstorageClient struct {
	cc grpc.ClientConnInterface
}

func NewMdstorageClient(cc grpc.ClientConnInterface) MdstorageClient {
	return &mdstorageClient{cc}
}

func (c *mdstorageClient) StoreMarkdown(ctx context.Context, in *protocol.Markdown, opts ...grpc.CallOption) (*StoreResult, error) {
	out := new(StoreResult)
	err := c.cc.Invoke(ctx, "/mdstorage.mdstorage/StoreMarkdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdstorageClient) UpdateMarkdown(ctx context.Context, in *protocol.Markdown, opts ...grpc.CallOption) (*StoreResult, error) {
	out := new(StoreResult)
	err := c.cc.Invoke(ctx, "/mdstorage.mdstorage/UpdateMarkdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdstorageClient) DeleteMarkdown(ctx context.Context, in *protocol.Markdown, opts ...grpc.CallOption) (*RemoveResult, error) {
	out := new(RemoveResult)
	err := c.cc.Invoke(ctx, "/mdstorage.mdstorage/DeleteMarkdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdstorageServer is the server API for Mdstorage service.
type MdstorageServer interface {
	StoreMarkdown(context.Context, *protocol.Markdown) (*StoreResult, error)
	UpdateMarkdown(context.Context, *protocol.Markdown) (*StoreResult, error)
	DeleteMarkdown(context.Context, *protocol.Markdown) (*RemoveResult, error)
}

// UnimplementedMdstorageServer can be embedded to have forward compatible implementations.
type UnimplementedMdstorageServer struct {
}

func (*UnimplementedMdstorageServer) StoreMarkdown(context.Context, *protocol.Markdown) (*StoreResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreMarkdown not implemented")
}
func (*UnimplementedMdstorageServer) UpdateMarkdown(context.Context, *protocol.Markdown) (*StoreResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarkdown not implemented")
}
func (*UnimplementedMdstorageServer) DeleteMarkdown(context.Context, *protocol.Markdown) (*RemoveResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMarkdown not implemented")
}

func RegisterMdstorageServer(s *grpc.Server, srv MdstorageServer) {
	s.RegisterService(&_Mdstorage_serviceDesc, srv)
}

func _Mdstorage_StoreMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Markdown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdstorageServer).StoreMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mdstorage.mdstorage/StoreMarkdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdstorageServer).StoreMarkdown(ctx, req.(*protocol.Markdown))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mdstorage_UpdateMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Markdown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdstorageServer).UpdateMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mdstorage.mdstorage/UpdateMarkdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdstorageServer).UpdateMarkdown(ctx, req.(*protocol.Markdown))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mdstorage_DeleteMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Markdown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdstorageServer).DeleteMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mdstorage.mdstorage/DeleteMarkdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdstorageServer).DeleteMarkdown(ctx, req.(*protocol.Markdown))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mdstorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mdstorage.mdstorage",
	HandlerType: (*MdstorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreMarkdown",
			Handler:    _Mdstorage_StoreMarkdown_Handler,
		},
		{
			MethodName: "UpdateMarkdown",
			Handler:    _Mdstorage_UpdateMarkdown_Handler,
		},
		{
			MethodName: "DeleteMarkdown",
			Handler:    _Mdstorage_DeleteMarkdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/mdstorage.proto",
}
