# Default values for env-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maibornwolff/madock8s_env_exporter
  tag: latest
  pullPolicy: Never

madock8sID: "envExporter"

annotations:
  githubExporter:
    githuburl: https://api.github.com/repos/MaibornWolff/madock8s/contents/exporter/env
  gitlabExporter:
    baseurl: "https://git.maibornwolff.de/api/v4/projects/3206/repository/"
    path: "exporter/env"
    recursive: "false"
    ref: "master"
    pattern: ".\\.md"
  envExporter:
    deployment: env-exporter

arguments: ['--storage-address', 'mdstorage:80']

env: 
  deletionStrategy: UPDATE

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
